---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
  #annotations:
  #  "storageclass.kubernetes.io/is-default-class": "true"
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
parameters:
  type: gp2

---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ds-snapshot-class
driver: ebs.csi.aws.com
deletionPolicy: Delete