config:
  clusters:
    - name: your-cluster
      short_description: "Your cluster"
      description: "Your EKS cluster"
      issuer: https://dex.platform.whatautomatech.com
      client_id: ${OIDC_GITHUB_CLIENT_ID}
      client_secret: ${OIDC_GITHUB_CLIENT_SECRET}
      redirect_uri: https://login.platform.whatautomatech.com/callback
      k8s_master_uri: https://${EKS_ENDPOINT}
      k8s_ca_pem: |
        -----BEGIN CERTIFICATE-----
        ${CLIENT_CERT}
        -----END CERTIFICATE-----

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: acme
  hosts:
    - host: login.platform.whatautomatech.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: dex-k8s-authenticator-tls
      hosts:
        - login.platform.whatautomatech.com