apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: deploykubeflow-cluster-role
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]