apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: s3admin-cluster-role
rules:
- apiGroups: ["*.s3.services.k8s.aws"]
  resources: ["*"]
  verbs: ["*"]