apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: user-example-com-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]