kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/name: am-client
  app.kubernetes.io/instance: am-client
  app.kubernetes.io/component: am-client
  app.kubernetes.io/part-of: forgerock
  tier: middle
  app: am
resources:
- deployment.yaml
- service.yaml
# - hpa.yaml

configMapGenerator:
- name: am-logback
  files:
  - config/logback.xml

generatorOptions:
  disableNameSuffixHash: true