apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
   # replace with the name of profile you want, this will be user's namespace name
   name: kubeflow-user-example-com
spec:
   owner:
       kind: User
       # replace with the email of the user
       name: user@example.com
   plugins:
     - kind: AwsIamForServiceAccount
       spec:
         awsIamRole: arn:aws:iam::${AWS_ACCOUNT_ID}:role/testenv-eks-cluster-role
