apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: s3admin-cluster-role-binding
subjects:
- kind: User
  name: s3admin # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: s3admin-cluster-role
  apiGroup: rbac.authorization.k8s.io