apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: user-example-com-cluster-role-binding-pipeline
subjects:
- kind: User
  name: user@example.com # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kubeflow-pipelines-edit
  apiGroup: rbac.authorization.k8s.io