apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1

managedNodeGroups:
  - name: on-demand
    labels: { role: workers }
    desiredCapacity: 2
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    instanceType: t2.micro
    #spot: true
    volumeSize: 20
    minSize: 1
    maxSize: 5

    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true