# An example of ClusterConfig object using an existing VPC:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1
  version: "1.27"

vpc:
  id: ${{ env.VPC_ID }}  # (optional, must match VPC ID used for each subnet below)
  cidr: "192.168.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availability zone as shown
    public:
      us-east-1d:
        id: "subnet-0b2512f8c6ae9bf30"
      us-east-1f:

managedNodeGroups:
  - name: ng-workers-1
    desiredCapacity: 1
    instanceTypes: [ "r4g.small" ]
    spot: true
    availabilityZones: ["us-east-1d"]
  - name: ng-workers-2
    desiredCapacity: 1
    instanceTypes: [ "r5.large" ]
    spot: true
    availabilityZones: [ "us-east-1f" ]