apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBSubnetGroup
metadata:
  name: kubeflow-db-subnet-group
spec:
  name: kubeflow-db-subnet-group
  description: Kubeflow DB Subnet Group
  subnetIDs: [${EKS_SUBNET_IDS}]
  tags: []