apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: kubeflow
  namespace: kubeflow
spec:
  allocatedStorage: 20 #min 20GB
  autoMinorVersionUpgrade: true
  backupRetentionPeriod: 7
  dbInstanceClass: db.t3.medium
  dbInstanceIdentifier: kubeflow
  dbName: kubeflow
  dbSubnetGroupName: kubeflow-db-subnet-group
  engine: mysql #aurora-postgresql
  engineVersion: "8.0"
  masterUsername: admin
  masterUserPassword:
    name: rds-secret
    namespace: kubeflow
    key: password
  multiAZ: false
  publiclyAccessible: false
  storageEncrypted: true
  storageType: gp3
  vpcSecurityGroupIDs: [${RDS_SECURITY_GROUP_ID}]