apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex-tls
  namespace: kube-system
spec:
  secretName: dex-tls
  dnsNames:
    - dex.platform.whatautomatech.com
  issuerRef:
    name: acme-staging
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex-k8s-authenticator-tls
  namespace: kube-system
spec:
  secretName: dex-k8s-authenticator-tls
  dnsNames:
    - login.platform.whatautomatech.com
  issuerRef:
    name: acme-staging
    kind: ClusterIssuer