kind: ClusterIssuer
apiVersion: cert-manager.io/v1
metadata:
  name: acme-staging
spec:
  acme:
    email: majinet@whatautomatech.com
    preferredChain: ''
    privateKeySecretRef:
      name: acme-staging
    server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
    solvers:
    - selector:
        dnsZones:
          - "whatautomatech.com"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z09610532JQ87Q4YP7X9H