bases:
- ../../base
patchesStrategicMerge:
- ingress.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: ingress-alb-parameters
  behavior: merge
  envs:
  - params.env
vars:
- name: certArn
  objref:
    kind: ConfigMap
    name: ingress-alb-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.certArn
namespace: ingress-nginx