configuration:
  database:
    password: flyteadmin
    host: flyteadmin.c7c9lvin3sa8.us-east-1.rds.amazonaws.com
    dbname: app  # what is this? why not flyteadmin or flyte?
  storage:
    metadataContainer: ack-flyte-bucket-${AWS_ACCOUNT_ID}
    userDataContainer: ack-flyte-bucket-userdata-${AWS_ACCOUNT_ID}
    provider: s3
    providerConfig:
      s3:
        region: ${AWS_REGION}
        authType: "iam"
  inline:
    plugins:
      k8s:
        inject-finalizer: true
        default-env-vars:
          - AWS_METADATA_SERVICE_TIMEOUT: 5
          - AWS_METADATA_SERVICE_NUM_ATTEMPTS: 20
    storage:
      cache:
        max_size_mbs: 20
        target_gc_percent: 100
serviceAccount:
  create: true
  annotations:
  eks.amazonaws.com/role-arn: ${SYS_ROLE_ARN}