apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1

managedNodeGroups:
  - name: on-demand
    amiFamily: Ubuntu2004
    labels: { role: workers }
    desiredCapacity: 2
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    instanceTypes: ["t3.medium"]
    spot: true
    volumeSize: 20
    minSize: 0
    maxSize: 5
    ssh:
      allow: false
      publicKeyName: eks_connect
      enableSsm: true

    iam:
      #instanceRoleARN: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/AmazonEKSNodeRole"
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        awsLoadBalancerController: true