apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1

managedNodeGroups:
  - name: on-demand
    #amiFamily: Ubuntu2004
    labels: { role: workers }
    desiredCapacity: 1
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    instanceTypes: ["t2.micro"]
    #spot: true
    volumeSize: 8
    minSize: 0
    maxSize: 5
    ssh:
      allow: false
      publicKeyName: eks_connect
      enableSsm: true

    iam:
      #instanceRoleARN: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/AmazonEKSNodeRole"
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        awsLoadBalancerController: true
  - name: console
    amiFamily: Ubuntu2004
    ami: ami-0261755bbcb8c4a84
    labels: {role: console}
    desiredCapacity: 1
    privateNetworking: true
    instanceTypes: ["t2.micro"]
    volumeSize: 8
    minSize: 0
    maxSize: 1
    ssh:
      allow: false
      publicKeyName: eks_connect
      enableSsm: true