kind: ClusterIssuer
apiVersion: cert-manager.io/v1
metadata:
  name: acme
spec:
  acme:
    email: majinet@whatautomatech.com
    preferredChain: ''
    privateKeySecretRef:
      name: acme-account-key
    server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
    solvers:
      - http01:
          ingress:
            class: nginx