controller:
    kind: Deployment
    # For testing and small installations one replica is sufficient. For larger tests
    # you may want to increase the replicas
    replicaCount: 1
    service:
        type: NodePort #LoadBalancer
        # externalTrafficPolicy: Local
        omitClusterIP: true
        #annotations:
        #  service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    publishService:
        enabled: true
    stats:
        enabled: true
        service:
            omitClusterIP: true
    nodeSelector:
        "frontend": "true"
    tolerations:
      - key: "WorkerAttachedToExtLoadBalancer"
        operator: "Exists"
        effect: "NoSchedule"
defaultBackend:
    service:
        omitClusterIP: true