name: Delete AWS CloudFormation Stack for Network

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
      stack-name:
        description: 'AWS CloudFormation Stack Name'
        required: true

jobs:
  vpc_aws:
    name: Delete AWS CloudFormation Stack for Network
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.NETWORK_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.NETWORK_AWS_SECRET_KEY }}
          aws-region: ${{ github.event.inputs.region}}
      - name: Configure environment name
        id: env-name
        env:
          REPO: ${{ github.repository }}
        run: |
          ENVIRONMENT=`echo $REPO | tr "/" "-"`
          echo "Environment name: $ENVIRONMENT"
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
      - name: Delete AWS CloudFormation Stack
        id: delete-stack
        run: |
          aws cloudformation delete-stack --stack-name ${{ github.event.inputs.stack-name}}