name: Step 1.5 - Provisioning VPC

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
      #keypair:
      #  description: 'SSH Key Pair'
      #  required: true

env:
  AWS_REGION : ${{ github.event.inputs.region}} #Change to reflect your Region
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

# Permission can be added at job level or workflow level
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  eks_aws:
    name: Provisioning VPC (Public and Private)
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/NetworkAdmin
          role-session-name: networkadmin
          aws-region: ${{ github.event.inputs.region}}
      - name: Configure environment name
        id: env-name
        env:
          REPO: ${{ github.repository }}
        run: |
          ENVIRONMENT=`echo $REPO | tr "/" "-"`
          echo "Environment name: $ENVIRONMENT"
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
      #- name: Allow passwordless sudo
      #  run: echo '${{ secrets.SUDO_PASSWORD }}' | sudo -Sv
      - name: install envsubst
        id: install-envsubst
        run: |
          curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst
          chmod +x envsubst
          sudo mv envsubst /usr/local/bin
      - name: Check CloudFormation stack existence (eks-vpc)
        id: check-stack-eks-vpc
        run: |
          if aws cloudformation describe-stacks --stack-name eks-vpc >/dev/null 2>&1; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
      - name: Create VPC
        if: steps.check-stack-eks-vpc.outputs.exists == 'false'
        run: |
          aws cloudformation create-stack --stack-name eks-vpc --template-body file://cloudformation/amazon-eks-vpc-private-subnets.yaml \
            --parameters ParameterKey=VpcBlock,ParameterValue=192.168.0.0/16 \
              ParameterKey=PublicSubnet01Block,ParameterValue=192.168.0.0/20 \
              ParameterKey=PublicSubnet02Block,ParameterValue=192.168.16.0/20 \
              ParameterKey=PrivateSubnet01Block,ParameterValue=192.168.32.0/20 \
              ParameterKey=PrivateSubnet02Block,ParameterValue=192.168.48.0/20
      - name: Check status of cloudformation (eks-vpc)
        run: |
          STACK_NAME="eks-vpc"
          INTERVAL_SECONDS=300

          while true; do
            STATUS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].StackStatus' --output text)
            echo "StackStatus: $STATUS"

            if [ "$STATUS" = "CREATE_COMPLETE" ]; then
              echo "Stack creation is complete."
              break
            fi

            echo "Sleeping for $INTERVAL_SECONDS seconds..."
            sleep $INTERVAL_SECONDS
          done
      - name: Set VPC ID
        id: set-vpc-id
        run: |
          VPC_ID=$(aws cloudformation describe-stacks --stack-name eks-vpc --query 'Stacks[0].Outputs[?OutputKey==`VpcId`].OutputValue' --output text)
          echo "VPC ID: $VPC_ID"
          echo "VPC_ID=$VPC_ID" >> $GITHUB_ENV
      - name: Check CloudFormation stack existence (aws-db-vpc)
        id: check-stack
        run: |
          if aws cloudformation describe-stacks --stack-name aws-db-vpc >/dev/null 2>&1; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
      - name: update cloudformation
        if: steps.check-stack.outputs.exists == 'false'
        run: |
          cat cloudformation/private-db-vpc-subnet-group.yaml | envsubst  > private-db-vpc-subnet-group.yaml
          cat private-db-vpc-subnet-group.yaml
      - name: Deploy DB VPC Subnet
        if: steps.check-stack.outputs.exists == 'false'
        run: |
          aws cloudformation create-stack --stack-name aws-db-vpc --template-body file://private-db-vpc-subnet-group.yaml
      - name: Check status of cloudformation (aws-db-vpc)
        run: |
          STACK_NAME="aws-db-vpc"
          INTERVAL_SECONDS=300

          while true; do
            STATUS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].StackStatus' --output text)
            echo "StackStatus: $STATUS"
          
            if [ "$STATUS" = "ROLLBACK_COMPLETE" ]; then
              echo "Stack rollback is complete."
              exit -1
            fi

            if [ "$STATUS" = "CREATE_COMPLETE" ]; then
              echo "Stack creation is complete."
              break
            fi

            echo "Sleeping for $INTERVAL_SECONDS seconds..."
            sleep $INTERVAL_SECONDS
          done
