name: Step 7.0 - Provisioning Kafka

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
      #keypair:
      #  description: 'SSH Key Pair'
      #  required: true

env:
  AWS_REGION : ${{ github.event.inputs.region}} #Change to reflect your Region
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  CLUSTER_NAME: eks-cluster

# Permission can be added at job level or workflow level
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  kafka_aws:
    name: Provisioning Kafka
    runs-on: ubuntu-20.04
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        path: main
      - name: Checkout awslabs kubeflow-manifests
        uses: actions/checkout@v3
        with:
          repository: strimzi/strimzi-kafka-operator
          ref: 0.36.0
          path: strimzi
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/KubeAdmin
          role-session-name: deploykubeflow
          aws-region: ${{ github.event.inputs.region}}
      - name: install envsubst
        id: install-envsubst
        run: |
          curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst
          chmod +x envsubst
          sudo mv envsubst /usr/local/bin
      - name: install eksctl
        id: install-eksctl
        run: |
          # for ARM systems, set ARCH to: `arm64`, `armv6` or `armv7`
          ARCH=amd64
          PLATFORM=$(uname -s)_$ARCH

          curl -sLO "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
          tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
          sudo mv /tmp/eksctl /usr/local/bin
      - name: install kubectl
        id: install-kubectl
        run: |
          curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.1/2023-04-19/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
          kubectl version --short --client
      - name: install yq
        id: install-yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update -y
          sudo apt install yq -y
      - name: Health Check Cluster
        id: health-check-eks
        run: |
          aws eks update-kubeconfig --name ${{env.CLUSTER_NAME}} --region ${{env.AWS_REGION}}
          kubectl config get-contexts
      - name: create namespace (kafka-operator)
        run: |
          kubectl create ns "kafka"
        continue-on-error: true
      - name: Designating Strimzi administrators
        run: |
          cd strimzi
          kubectl create -f install/strimzi-admin
      - name: Deploying the Cluster Operator to watch a single namespace
        run: |
          sed -i 's/namespace: .*/namespace: kafka-operator/' install/cluster-operator/*RoleBinding*.yaml
          kubectl create -f install/cluster-operator -n kafka
      - name: Deploying the Kafka cluster
        run: |
          #yq -i '.spec.kafka.storage.volumes[0].size = "20Gi"' examples/kafka/kafka-persistent-single.yaml
          #yq -i '.spec.zookeeper.storage.size = "20Gi"' examples/kafka/kafka-persistent-single.yaml
          kubectl apply -f main/config/kafka/kafka.yaml -n kafka
      - name: Building Kafka Connect
        run: |
          kubectl create secret docker-registry ecr-secret \
            --docker-server=${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com \
            --docker-username=AWS \
            --docker-password=$(aws ecr get-login-password) \
            --namespace=default
          
          cat main/deployments/connector/camel-aws-sqs-kakfa-connect.yaml | envsubst  > camel-aws-sqs-kakfa-connect.yaml
          
          kubectl apply -f camel-aws-sqs-kakfa-connect.yaml
          kubectl apply -f main/deployments/connector/camel-aws-sqs-source-kakfa-connector.yaml
